// THE RITUAL — Adam Nevill | ENLACES — Prólogo–Cap.20

const links = [
    { source: `root`, target: `cat-personajes`, label: ``, type: `cat` },
    { source: `root`, target: `cat-eventos`, label: ``, type: `cat` },
    { source: `root`, target: `cat-concepto`, label: ``, type: `cat` },
    { source: `root`, target: `cat-lugar`, label: ``, type: `cat` },
    { source: `root`, target: `cat-trama`, label: ``, type: `cat` },
    { source: `hutch`, target: `cat-personajes`, label: ``, type: `arc` },
    { source: `luke`, target: `cat-personajes`, label: ``, type: `arc` },
    { source: `dom`, target: `cat-personajes`, label: ``, type: `arc` },
    { source: `phil`, target: `cat-personajes`, label: ``, type: `arc` },
    { source: `prologue-carcass`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `decision-new-route`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `lost-in-forest`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `house-found`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `sound-in-trees`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `house-entry`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `house-interior`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `phil-upstairs-scare`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `goat-effigy-discovered`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `goat-of-mendes`, target: `cat-concepto`, label: ``, type: `arc` },
    { source: `stuga-fritidshus`, target: `cat-concepto`, label: ``, type: `arc` },
    { source: `box-bed`, target: `cat-concepto`, label: ``, type: `arc` },
    { source: `rune-carvings`, target: `cat-concepto`, label: ``, type: `arc` },
    { source: `skull-display`, target: `cat-concepto`, label: ``, type: `arc` },
    { source: `crucifix-display`, target: `cat-concepto`, label: ``, type: `arc` },
    { source: `the-forest`, target: `cat-concepto`, label: ``, type: `arc` },
    { source: `animal-sacrifice`, target: `cat-concepto`, label: ``, type: `arc` },
    { source: `laponia-sueca`, target: `cat-lugar`, label: ``, type: `arc` },
    { source: `el-bosque-loc`, target: `cat-lugar`, label: ``, type: `arc` },
    { source: `la-casa`, target: `cat-lugar`, label: ``, type: `arc` },
    { source: `skaite`, target: `cat-lugar`, label: ``, type: `arc` },
    { source: `gammelstad`, target: `cat-lugar`, label: ``, type: `arc` },
    { source: `skansen`, target: `cat-lugar`, label: ``, type: `arc` },
    { source: `trama-quien-cuelga-el-animal`, target: `cat-trama`, label: ``, type: `arc` },
    { source: `trama-culto-activo`, target: `cat-trama`, label: ``, type: `arc` },
    { source: `trama-supervivencia`, target: `cat-trama`, label: ``, type: `arc` },
    { source: `hutch`, target: `luke`, label: `mejor amigo (distante)`, type: `rel` },
    { source: `hutch`, target: `dom`, label: `amigo más cercano`, type: `rel` },
    { source: `hutch`, target: `phil`, label: `amigo universitario`, type: `rel` },
    { source: `hutch`, target: `decision-new-route`, label: `decide el atajo`, type: `event` },
    { source: `hutch`, target: `prologue-carcass`, label: `descubre / no tiene respuesta`, type: `event` },
    { source: `hutch`, target: `house-found`, label: `fuerza la entrada`, type: `event` },
    { source: `hutch`, target: `goat-effigy-discovered`, label: `identifica / fotografía`, type: `event` },
    { source: `hutch`, target: `goat-of-mendes`, label: `identifica como`, type: `lore` },
    { source: `hutch`, target: `box-bed`, label: `reconoce por Skansen`, type: `lore` },
    { source: `hutch`, target: `skansen`, label: `visitó antes`, type: `rel` },
    { source: `hutch`, target: `laponia-sueca`, label: `organiza la expedición`, type: `event` },
    { source: `luke`, target: `prologue-carcass`, label: `descubre / calla`, type: `event` },
    { source: `luke`, target: `decision-new-route`, label: `advierte riesgos / cede`, type: `event` },
    { source: `luke`, target: `sound-in-trees`, label: `único testigo`, type: `event` },
    { source: `luke`, target: `house-found`, label: `desconfía / resiste`, type: `event` },
    { source: `luke`, target: `goat-effigy-discovered`, label: `sube / presencia`, type: `event` },
    { source: `luke`, target: `the-forest`, label: `percibe como agente`, type: `trama` },
    { source: `luke`, target: `gammelstad`, label: `vio runas allí`, type: `lore` },
    { source: `dom`, target: `prologue-carcass`, label: `descubre`, type: `event` },
    { source: `dom`, target: `lost-in-forest`, label: `rodilla lesionada`, type: `event` },
    { source: `dom`, target: `house-found`, label: `insiste en entrar`, type: `event` },
    { source: `phil`, target: `prologue-carcass`, label: `descubre`, type: `event` },
    { source: `phil`, target: `house-entry`, label: `primero en entrar`, type: `event` },
    { source: `phil`, target: `house-interior`, label: `comenta crucifijos`, type: `event` },
    { source: `phil`, target: `phil-upstairs-scare`, label: `protagoniza`, type: `event` },
    { source: `phil`, target: `goat-effigy-discovered`, label: `primer contacto (sin saber)`, type: `event` },
    { source: `prologue-carcass`, target: `decision-new-route`, label: `4h antes (cronología)`, type: `arc` },
    { source: `decision-new-route`, target: `lost-in-forest`, label: `consecuencia`, type: `arc` },
    { source: `lost-in-forest`, target: `house-found`, label: `sendero inesperado`, type: `arc` },
    { source: `house-found`, target: `house-entry`, label: `forzada por Hutch`, type: `arc` },
    { source: `house-entry`, target: `sound-in-trees`, label: `simultáneo`, type: `arc` },
    { source: `house-entry`, target: `house-interior`, label: `exploración`, type: `arc` },
    { source: `house-interior`, target: `phil-upstairs-scare`, label: `Phil sube solo`, type: `arc` },
    { source: `phil-upstairs-scare`, target: `goat-effigy-discovered`, label: `Hutch y Luke suben`, type: `arc` },
    { source: `goat-effigy-discovered`, target: `goat-of-mendes`, label: `identificada como`, type: `lore` },
    { source: `goat-effigy-discovered`, target: `box-bed`, label: `sienta sobre`, type: `lore` },
    { source: `goat-effigy-discovered`, target: `rune-carvings`, label: `rodeada de`, type: `lore` },
    { source: `goat-effigy-discovered`, target: `animal-sacrifice`, label: `rodeada de`, type: `lore` },
    { source: `house-interior`, target: `skull-display`, label: `contiene`, type: `lore` },
    { source: `house-interior`, target: `crucifix-display`, label: `contiene`, type: `lore` },
    { source: `house-found`, target: `stuga-fritidshus`, label: `anti-arquetipo de`, type: `lore` },
    { source: `lost-in-forest`, target: `the-forest`, label: `el bosque los dirige`, type: `trama` },
    { source: `sound-in-trees`, target: `the-forest`, label: `origen del ruido`, type: `trama` },
    { source: `prologue-carcass`, target: `the-forest`, label: `ocurre en`, type: `trama` },
    { source: `decision-new-route`, target: `el-bosque-loc`, label: `entra en`, type: `event` },
    { source: `decision-new-route`, target: `skaite`, label: `destino propuesto`, type: `event` },
    { source: `house-found`, target: `la-casa`, label: `la localizan`, type: `event` },
    { source: `prologue-carcass`, target: `el-bosque-loc`, label: `4 km al oeste de la casa`, type: `event` },
    { source: `el-bosque-loc`, target: `laponia-sueca`, label: `parte de`, type: `arc` },
    { source: `la-casa`, target: `el-bosque-loc`, label: `en claro dentro de`, type: `arc` },
    { source: `rune-carvings`, target: `gammelstad`, label: `similares a runas de`, type: `lore` },
    { source: `box-bed`, target: `skansen`, label: `Hutch los vio en`, type: `lore` },
    { source: `la-casa`, target: `skull-display`, label: `contiene`, type: `lore` },
    { source: `la-casa`, target: `crucifix-display`, label: `contiene`, type: `lore` },
    { source: `la-casa`, target: `goat-of-mendes`, label: `templo a`, type: `lore` },
    { source: `trama-quien-cuelga-el-animal`, target: `prologue-carcass`, label: `sin resolver`, type: `trama` },
    { source: `trama-quien-cuelga-el-animal`, target: `sound-in-trees`, label: `posible respuesta`, type: `trama` },
    { source: `trama-culto-activo`, target: `goat-effigy-discovered`, label: `evidencia`, type: `trama` },
    { source: `trama-culto-activo`, target: `la-casa`, label: `sede del culto`, type: `trama` },
    { source: `trama-supervivencia`, target: `lost-in-forest`, label: `origen del problema`, type: `trama` },
    { source: `trama-supervivencia`, target: `la-casa`, label: `refugio nocturno`, type: `trama` },
    { source: `camp-night-ch11`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `night-terrors`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `morning-escape-house`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `runes-on-trees-discovery`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `two-buildings-found`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `luke-scouts-ahead`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `standing-stone-found`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `compass-deviation-ch20`, target: `cat-eventos`, label: ``, type: `arc` },
    { source: `boreal-forest`, target: `cat-concepto`, label: ``, type: `arc` },
    { source: `forest-silence`, target: `cat-concepto`, label: ``, type: `arc` },
    { source: `asentamiento-abandonado`, target: `cat-lugar`, label: ``, type: `arc` },
    { source: `piedra-runica`, target: `cat-lugar`, label: ``, type: `arc` },
    { source: `trama-que-causo-pesadillas`, target: `cat-trama`, label: ``, type: `arc` },
    { source: `goat-effigy-discovered`, target: `camp-night-ch11`, label: `misma noche`, type: `arc` },
    { source: `camp-night-ch11`, target: `night-terrors`, label: `esa misma noche`, type: `arc` },
    { source: `night-terrors`, target: `morning-escape-house`, label: `consecuencia inmediata`, type: `arc` },
    { source: `morning-escape-house`, target: `runes-on-trees-discovery`, label: `Phil lo descubre antes de salir`, type: `arc` },
    { source: `runes-on-trees-discovery`, target: `two-buildings-found`, label: `2h despues, mismo sendero`, type: `arc` },
    { source: `two-buildings-found`, target: `luke-scouts-ahead`, label: `Luke va por delante`, type: `arc` },
    { source: `luke-scouts-ahead`, target: `standing-stone-found`, label: `30 min despues`, type: `arc` },
    { source: `two-buildings-found`, target: `compass-deviation-ch20`, label: `silencio empieza aqui`, type: `arc` },
    { source: `hutch`, target: `night-terrors`, label: `sonambulo / arrodillado ante efigie`, type: `event` },
    { source: `hutch`, target: `morning-escape-house`, label: `decide ruta / lidera salida`, type: `event` },
    { source: `hutch`, target: `runes-on-trees-discovery`, label: `identifica las runas`, type: `event` },
    { source: `hutch`, target: `compass-deviation-ch20`, label: `descubre la desviacion`, type: `event` },
    { source: `hutch`, target: `boreal-forest`, label: `explica el ecosistema`, type: `lore` },
    { source: `luke`, target: `night-terrors`, label: `pesadilla / rescata a los tres`, type: `event` },
    { source: `luke`, target: `camp-night-ch11`, label: `teoriza sobre el bosque`, type: `event` },
    { source: `luke`, target: `luke-scouts-ahead`, label: `protagoniza`, type: `event` },
    { source: `luke`, target: `standing-stone-found`, label: `descubre`, type: `event` },
    { source: `dom`, target: `night-terrors`, label: `encontrado en el prado`, type: `event` },
    { source: `phil`, target: `night-terrors`, label: `encontrado desnudo en la despensa`, type: `event` },
    { source: `phil`, target: `runes-on-trees-discovery`, label: `primero en notar las runas`, type: `event` },
    { source: `night-terrors`, target: `goat-effigy-discovered`, label: `la efigie pudo desencadenarlas`, type: `trama` },
    { source: `night-terrors`, target: `la-casa`, label: `ocurre dentro y alrededor`, type: `lore` },
    { source: `runes-on-trees-discovery`, target: `rune-carvings`, label: `extiende el concepto al exterior`, type: `lore` },
    { source: `runes-on-trees-discovery`, target: `la-casa`, label: `rodea la casa en circulo`, type: `lore` },
    { source: `forest-silence`, target: `the-forest`, label: `manifestacion activa de`, type: `trama` },
    { source: `forest-silence`, target: `compass-deviation-ch20`, label: `precede a la desviacion`, type: `arc` },
    { source: `boreal-forest`, target: `the-forest`, label: `contexto cientifico de`, type: `lore` },
    { source: `boreal-forest`, target: `el-bosque-loc`, label: `describe el ecosistema de`, type: `lore` },
    { source: `camp-night-ch11`, target: `the-forest`, label: `Luke teoriza sobre`, type: `trama` },
    { source: `two-buildings-found`, target: `asentamiento-abandonado`, label: `lo identifican`, type: `event` },
    { source: `standing-stone-found`, target: `piedra-runica`, label: `la descubre`, type: `event` },
    { source: `piedra-runica`, target: `el-bosque-loc`, label: `dentro del bosque`, type: `arc` },
    { source: `asentamiento-abandonado`, target: `el-bosque-loc`, label: `dentro del bosque`, type: `arc` },
    { source: `asentamiento-abandonado`, target: `la-casa`, label: `conectados por el mismo sendero`, type: `lore` },
    { source: `trama-que-causo-pesadillas`, target: `night-terrors`, label: `sin resolver`, type: `trama` },
    { source: `trama-que-causo-pesadillas`, target: `goat-effigy-discovered`, label: `posible fuente`, type: `trama` },
    { source: `trama-que-causo-pesadillas`, target: `la-casa`, label: `espacio donde ocurre`, type: `trama` },
    { source: `trama-supervivencia`, target: `compass-deviation-ch20`, label: `nuevo obstaculo`, type: `trama` },
    { source: `trama-supervivencia`, target: `standing-stone-found`, label: `nuevo hallazgo`, type: `trama` },
    { source: `trama-culto-activo`, target: `runes-on-trees-discovery`, label: `evidencia adicional`, type: `trama` },
    { source: `trama-culto-activo`, target: `piedra-runica`, label: `posible marcador del recinto`, type: `trama` },
    { source: `trama-quien-cuelga-el-animal`, target: `night-terrors`, label: `dom: put us up there`, type: `trama` }
];
