// THE RITUAL — Adam Nevill | RESÚMENES — Caps. Prólogo–20

const chapterSummaries = [
  {
    chapter: 0,
    title: `Prólogo — El Animal en el Árbol`,
    summary: `Segundo día de la excursión. Lluvia intensa, cielo gris bajo, pérdida de orientación progresiva. Los cuatro amigos trepan sobre otro árbol caído, empujan por el helecho y se detienen en seco. Sobre sus cabezas, a la altura máxima de un hombre erguido, cuelga algo de las ramas de un abeto. La caja torácica enorme; las vísceras azuladas colgando; la piel extendida sobre las ramas como una carpa rasgada; la mandíbula ósea y el ojo — tan grande como una bola de billar, opaco. Sin olor: matanza reciente.<br><br>Hutch palidece. Phil tiembla al hablar. Dom pregunta por qué alguien lo pondría ahí arriba. Luke no dice nada. El grupo abandona el lugar más deprisa de lo que llegó. Pronto la voz les devuelve suficiente coraje para hablar, aunque sus pasos hacen más ruido que en cualquier otro momento de los dos días anteriores. El texto cierra con el dato más inquietante: <em>It was a fresh kill.</em>`
  },
  {
    chapter: 1,
    title: `Capítulo 1 — Cuatro Horas Antes`,
    summary: `Al mediodía, Hutch para y observa a los otros tres desde lejos: hombros encogidos, cabezas bajas, derrotados. Llama a Luke aparte para una "judgement call." Dom tiene la rodilla inflamada del primer día; Phil lleva vaqueros empapados y los pies en carne viva desde el primer campamento.<br><br>Hutch propone el atajo: abandonar el sendero Sörstubba, cruzar la franja de bosque hacia el sureste, alcanzar el Río Stora Luleälven al anochecer, bajar a las cabañas de Skaite. "Un par de horas por la parte más estrecha." Luke plantea sus objeciones: terreno desconocido, pantanos marcados en el mapa, nadie sabe que van allí (la oficina de Porjus estaba cerrada). Hutch descarta cada una. Luke cede: "You're the boss."<br><br>En el fondo, Hutch ve cuánta rabia lleva Luke acumulada últimamente — sus llamadas derivan siempre en diatribas — y teme que explote contra Dom y Phil, lo que pondría en peligro la cohesión del grupo. El objetivo ya no es salvar las vacaciones: es garantizar que todos lleguen a casa sanos.`
  },
  {
    chapter: 2,
    title: `Capítulo 2 — Cuatro Horas y Veinte Minutos Después`,
    summary: `El grupo corre en parte, avanza en parte, alejándose del animal en el árbol. Phil cae en las ortigas pero se levanta sin quejarse y trota para alcanzar a los otros. En un pequeño claro marrón se detienen exhaustos.<br><br>Luke intenta encender un cigarrillo — cuatro intentos con el Zippo, por fin lo consigue. Propone la hipótesis del lobo: lo mató pero algo lo puso en el árbol. Dom pregunta, otra vez, por qué. Hutch especula sobre cazadores o granjeros pero los descarta: es Parque Nacional, sin actividad cultivada. La hipótesis de Luke sobre el oso — que lo habría colgado para proteger la presa de carroñeros en el suelo — queda flotando sin confirmación.<br><br>La conversación termina sin respuesta. El grupo retoma la marcha. El bosque sigue igual de oscuro y enmarañado.`
  },
  {
    chapter: 3,
    title: `Capítulo 3 — El Bosque los Conduce`,
    summary: `El río no aparece. La tarde pasa; la luz bajo el dosel cambia de gris fino a gris espeso. Hutch consulta el mapa por quinta vez en una hora. Por la mañana sabía exactamente dónde estaban — ahora ya no sabe ni en qué parte del bosque se encuentran. No anticipó ni la densidad del sotobosque ni los terrenos rotos.<br><br>El problema más inquietante: el bosque los lleva en dirección noroeste cuando necesitan ir sureste. Solo pueden moverse donde la vegetación abre paso, que casi nunca es hacia donde quieren ir. <em>"The forest was leading them."</em> Han torcido a todos los puntos del compás para evitar obstáculos. Necesitarían corregir constantemente, y Hutch no lo hizo. Dom ya no puede doblar la rodilla.<br><br>Hutch considera dar marcha atrás — pero eso significa pasar de noche por el árbol con la carcasa. Luke fuma sin parar; sus labios se mueven solos. Hutch identifica ambas como señales de alarma en Luke.`
  },
  {
    chapter: 4,
    title: `Capítulo 4 — La Casa`,
    summary: `Poco antes de las siete de la tarde, tras cuatro kilómetros adicionales por ivy, ortigas y ramas rotas, el bosque les corta su primer descanso: un sendero estrecho, lo suficientemente ancho para caminar erguidos en fila india. Hutch elige la dirección este para intentar compensar el desvío noroeste. El sendero lleva a una casa.<br><br>La descripción exterior es la negación exacta del arquetipo de la stuga sueca: paredes abultadas y ennegrecidas, tejas caídas, ventanas entablilladas contra inviernos pasados, sin simetría, sin color. Patio delantero cubierto de ortigas hasta la rodilla. Phil dice "It's empty. Let's get in there" y avanza — pero algo lo detiene a pocos metros. Luke, que ha desconfiado desde el primer vistazo, propone seguir: todavía hay una hora de luz. Dom y Phil lo ignoran; Dom añade que Luke puede quedarse fuera con "el lobo que le dio una buena paliza al alce." Hutch zanja el debate con pragmatismo: hay chimenea, hay que secarse.`
  },
  {
    chapter: 5,
    title: `Capítulo 5 — La Entrada`,
    summary: `Luke se queda en el patio mientras los otros empujan la puerta. Hutch necesita varios golpes de bota alrededor del pomo de hierro negro para vencer la madera hinchada. Luke enciende un cigarrillo. Discute en voz baja consigo mismo sobre Dom y Phil: el colapso de lo que alguna vez fue una amistad real en quince años. Recuerda la noche previa al vuelo en Londres: no pudo mantener una conversación con ninguno de los dos. Un nudo en la garganta.<br><br>Hutch sale y lo mira. "Chieftain" — su palabra de código para decirle a Luke que se calme. Hutch argumenta: no tienen elección, la temperatura bajará, están empapados. "We'd never do it in a tent."<br><br>Luke va a entrar — y entonces escucha el ruido: un estallido tremendo de madera fresca rompiéndose en el bosque. Como una rama gruesa arrancada de tajo del tronco. El eco se pierde adentrándose en los árboles. Luke se queda paralizado, imaginando una fuerza y una rabia enormes ahí fuera. El trueno lo devuelve a la realidad. Hutch lo llama de nuevo. Luke informa: "The trees. In the trees. Did you not hear it?" Hutch lo atribuye al trueno. Luke entra.`
  },
  {
    chapter: 6,
    title: `Capítulo 6 — La Planta Baja`,
    summary: `La planta baja se descubre bajo el haz de cuatro linternas. Primer impacto: cráneos. Docenas de ellos — de pájaros, ardillas, armiños, fijados con clavos oxidados. Cráneos de lince, ciervo y alce en el suelo o todavía colgando junto al techo bajo, algunos rotos. Entre los cráneos, al menos doce crucifijos hechos a mano de ramitas y hilo, la mayoría ladeados o al revés. Dom los llama "evil Christian shit."<br><br>Hutch examina el anexo lateral: herramientas, incluyendo una guadaña de aspecto amenazante. Estima la antigüedad en ~100 años. Ataca la estufa de hierro oxidada con su navaja de Estocolmo. Dom reclama el único taburete. Phil prueba la mesa con las manos. Luke, el más alto, se golpea la cabeza con una de las lámparas de aceite corroídas que cuelgan de las vigas. Los otros se ríen. El humor rompe la tensión un momento. Phil, de pie en sus calcetines, señala los crucifijos: <em>"You'd think they'd make you feel safe. But they don't."</em>`
  },
  {
    chapter: 7,
    title: `Capítulo 7 — La Escalera`,
    summary: `Phil decide explorar el piso de arriba ("Think I might go and check out the bedrooms"). Hutch bromea con el "en suite." Luke se queda junto a la puerta, observando la lluvia. Dom y Hutch continúan con la estufa y las botas.<br><br>El rayo ilumina el suelo de madera polvoriento cerca de la puerta abierta. Phil toca uno de los crucifijos al subir: <em>"You'd think they'd make you feel safe. But they don't."</em> — la frase más significativa pronunciada en la casa hasta ahora. Afuera, el trueno muele hierro contra granito. La tormenta directamente encima.`
  },
  {
    chapter: 8,
    title: `Capítulo 8 — Phil Baja`,
    summary: `Phil baja las escaleras tan rápido que suena como una caída. Sus jadeos asmáticos preceden a cualquier descripción de lo que vio. Llega al final de la escalera, cae de rodillas, gira sobre el trasero, se arrastra alejándose de los peldaños. Tres pares de ojos se giran; tres linternas apuntan a la base de la escalera. Phil intenta gritar, le sale un aullido. Dice: "Something's up there!" Pausa. Luego: "I don't know! I saw it. In the bed."<br><br>El grupo debate en voz baja. Dom quiere salir ya. Hutch racionaliza: sin huellas, lleno de polvo, los ratones se habrían oído. Phil describe lo poco que recuerda: "Some eyes in my torchlight. And something black. Something big. But it didn't move. It just sat there and stared at me." Hutch evalúa: no pueden salir — tormenta, temperatura, la oscuridad. "We can't go back out in this." Luke sonríe por primera vez en horas: <em>"You first then."</em>`
  },
  {
    chapter: 9,
    title: `Capítulo 9 — Hutch y Luke Suben`,
    summary: `La escalera cruje y retumba con cada paso. Imposible hacerlo en silencio. Hutch primero, linterna en una mano, navaja en la otra. Luke inmediatamente detrás — pero no tan cerca que no pueda girar y bajar corriendo si Hutch se mueve de golpe. La linterna de Luke ilumina los patrones de la madera antigua en las paredes — caras con barba larga que no son más que vetas del grano oscurecido. Antigüedad de museo. Luke piensa en las personas que vivieron aquí sin luz eléctrica en ese bosque; la imagen lo aplasta: uno habría muerto primero, el otro habría vivido solo en una desesperación que "just to know it for a moment would make your heart burst."<br><br>Hutch llega al recodo de la escalera y se detiene. Hombros caídos, cabeza inclinada hacia adelante. Lo ve. El perfil de Hutch cambiado: pálido y tenso "like he'd received bad news." Luke sube los últimos dos peldaños. Se vuelve hacia el desván. Sus dos linternas apuntan al fondo.`
  },
  {
    chapter: 10,
    title: `Capítulo 10 — La Efigie`,
    summary: `Al fondo del desván, entre los dos lados del tejado, la silueta. Sentada. Inmóvil. La linterna de Luke sube por los cuernos largos y gruesos, las cuencas oculares vacías, los labios negros retraídos sobre dientes amarillos. La piel negra brilla donde la lluvia la ha mojado. Las patas traseras posadas sobre los bordes del pequeño féretro de madera, pezuñas listas para levantarse. Las tetinas rosadas en el pecho — <em>"This was the most unpleasant thing of all."</em><br><br>Los brazos delanteros alzados a altura de hombros, palmas hacia arriba. Hutch baja la linterna y ve las manos: <strong>humanas. Momificadas. Ennegrecidas. Cosidas al cuerpo de la cabra.</strong> La linterna de Hutch rastrea el suelo: huesos de conejos y aves, algunos todavía cubiertos de piel seca como papel. Luego las vigas del techo: símbolos tallados a fondo en la madera, a distintas alturas, en líneas largas.<br><br>Hutch camina hacia la efigie. Luke se estremece con cada paso. <em>"If it moved, my heart would stop."</em> Hutch se inclina, examina la parte trasera: los ratones han trabajado la taxidermia. Gira hacia Luke con los ojos brillando en la luz: "The little hands are human. Mummified. Stitched on." Su conclusión: algún tipo de templo, ofrenda y sacrificio. La identifica: <em>"The Goat of Mendes."</em> Dictamina: <em>"Swedish lunacy. It's the darkness and the long nights. Send anyone mad."</em><br><br>Hutch reconoce además el "féretro": es un lecho-caja tradicional escandinavo — lo vio en Skansen y en Noruega. La caja donde dormían familias, ahora trono de un ídolo pagano con manos de muerto cosidas. Hutch fotografía la escena. Bajan.`
  },
  {
    chapter: 11,
    title: `Capítulo 11 — Hoguera y Teorías`,
    summary: `La jornada más exigente hasta ahora pese a recorrer menos distancia. Cena con las últimas latas (salchichas con alubias, sopa de pollo en polvo), dos barritas cada uno — siguen con hambre, lamen los cuencos por primera vez. El Jack Daniel's de Dom, la mayor parte para él. Hutch empuja la última pata de la silla dentro de la estufa; Phil y Dom ya habían roto el taburete pese a Luke. Cuatro crucifijos como yesca — Luke mira hacia otro lado.<br><br>En la luz rojiza de las llamas, Luke observa a sus amigos. Dom envejeciendo rápidamente (sienes grises, ojeras de hombre mayor), sin mencionar a su esposa Gayle en todo el viaje, bebe en cualquier ocasión. Phil completamente dejado — el éxito inmobiliario no ha traído felicidad; Luke sospecha que Michelle, su esposa, es la causa. Dato que el lector recibe pero Phil no sabe: Luke se acostó con Michelle hace 16 años en la Easter Ball, antes de que Phil la conociera.<br><br>Conversación alrededor del fuego: la discusión sobre el animal en el árbol lleva a Luke a su teoría más articulada — <em>"el bosque hizo que esta gente enloqueciera... no creo que la gente deba venir aquí."</em> Hutch admite, sin ironía, que jamás ha visto nada parecido. Luke acuña: <em>"The blasted heath. The cursed wood."</em><br><br>Tarde en la noche, Luke y Hutch hablan en voz baja. Hutch confiesa que no tiene ningún plan. De acuerdo en que el lugar seguiría siendo aterrador aunque hiciera sol. Luke verbaliza la idea que no puede dejar de pensar: la efigie del desván como representación de lo que colgó la carcasa en el árbol. Phil, aparentemente dormido: <em>"I heard that."</em>`
  },
  {
    chapter: 12,
    title: `Capítulo 12 — La Pesadilla de Luke`,
    summary: `Narrado en segunda persona del singular — el lector ocupa el cuerpo de Luke dentro del sueño. Estás colgado entre las ramas y las zarzas del bosque completamente oscuro, enterrado hasta las rodillas en grietas, incapaz de arrancar los pies del suelo. La criatura avanza a grandes zancadas: cuernos moteados negros descascarados, dientes amarillos para desgarrar, encías de perro negro, un bramido de novillo que desciende a gemido nasal húmedo y asciende de octava hasta el <em>yip yip yip</em> de la caza solitaria. Sabes que vendrán los cuernos primero — una embestida en el torso denso antes de los dientes. Gritas en la oscuridad. Nadie te oye. Las ancas y los flancos se endurecen en músculo, el cuello largo avanza. Un último jadeo de aire fétido, animal, caliente con carne podrida, desde atrás.<br><br>Luke se despierta jadeando. La piel le duele como si hubiera corrido entre zarzas. Mira alrededor: tres sacos de dormir vacíos y abiertos. Los otros no están. Escucha sollozos. Desde el piso de arriba.`
  },
  {
    chapter: 13,
    title: `Capítulo 13 — Hutch en el Desván`,
    summary: `Narrado también en segunda persona — esta vez el "tú" es Hutch, arrodillado en el desván, llorando con los ojos ya secos. La cosa sobre su trono de madera, los cuernos largos rozando el techo, los brazos lanzados hacia arriba en triunfo hidioso. Hutch espera su fin.<br><br>Una mano en el hombro. La voz de Luke. Hutch levanta la vista — el reconocimiento de la cara de su amigo hace que su cara se arrugue en un espasmo de llanto sin lágrimas. La boca sabe a sal caliente. Luke lo levanta. Hutch mira hacia donde estaba la amenaza: la efigie en la oscuridad, con el tenue contorno de los cuernos. <em>"No está viva. Es un animal. Disecado y comido por los ratones."</em> Luke: <em>"Tenemos que salir de aquí. Ahora."</em>`
  },
  {
    chapter: 14,
    title: `Capítulo 14 — Dom en el Prado`,
    summary: `Hutch y Luke salen a buscar a los demás. Dom está en el prado delante de la casa, arrodillado en la hierba larga y húmeda con solo la ropa interior y una camiseta. Cara sin color bajo la suciedad. Labios oscuros. Ojos vidriosos, fijos en los árboles. Lágrimas en los surcos de las mejillas, ya frías. Completamente ajeno a la presencia de los otros dos.<br><br>Hutch y Luke son incapaces de tocarlo. Jamás lo han visto así. Siguen su mirada hacia el bosque — no ven nada. Solo madera oscura, verdor chorreante, el brillo blanquecino de corteza de abedul.<br><br>Hutch llama: <em>"Domja. Domja."</em> Dom, sin girar la cabeza: <em>"It's going to put us up there, in the trees."</em> Silencio. Luke gira hacia la casa: <em>"Tenemos que encontrar a Phil."</em>`
  },
  {
    chapter: 15,
    title: `Capítulo 15 — Phil en la Despensa`,
    summary: `Phil está en el anexo de herramientas — la despensa — de pie, desnudo, acorralado en un rincón. Casi luminoso en las sombras. Sus ojos fijos en algo que no existe en el espacio visible, ligeramente por encima y detrás de los que le buscan. Ambos brazos levantados en una posición indecisa — como si hubiera intentado defenderse pero la idea de resistir le pareciera ya inútil. Labios temblando. Hutch le toca los dedos: Phil gime y hunde la cabeza entre los hombros. Olor a orina rancia en la madera húmeda.<br><br>Hutch lo lleva afuera cubriéndole los hombros con su impermeable azul. La brisa y el aire frío lo reviven. Tres sollozos poderosos e incongruentes, que suenan extraños viniendo de él. Luego está de pie ante ellos, parpadeando. Sus ojos preguntan desesperadamente — no recibe respuesta ni comprensión.<br><br>Hutch, girándose hacia la casa: <em>"Vamos. Recojamos y salgamos."</em> Luke: <em>"Amén."</em> Dom: <em>"What the fuck?"</em> Luke: <em>"Ya os dije que era mala idea. Quién sabe lo que hemos removido."</em>`
  },
  {
    chapter: 16,
    title: `Capítulo 16 — El Bosque Impenetrable y los Pinos Rúnicos`,
    summary: `Mañana. El bosque es impenetrable en dirección sur. Dom arranca un sauce enano — la rama lo quema y lo enmantequilla pero no cede. Hutch explica: bosque boreal virgen, nunca gestionado, los pinos escoceses pueden vivir 600 años, solo científicos entran tan adentro. Dom: <em>"If it wasn't so wet I'd set fire to the bitch. Burn our way out."</em><br><br>En la calma relativa, Luke suelta una carcajada cuando Hutch menciona que lo encontraron <em>"kneeling before the goat."</em> La risa suena inapropiada en el bosque callado, como reírse en una iglesia. Hutch sonríe: <em>"Jesus, boys. How are we going to P.R. this when we get home?"</em><br><br>Phil, que lleva callado toda la mañana, habla de espaldas a todos desde el lado norte del claro: <em>"It's on all of the trees. Goes in a circle. Round the house. On the old ones."</em> Todos se giran a mirar.`
  },
  {
    chapter: 17,
    title: `Capítulo 17 — Runas y Debate de Ruta`,
    summary: `Hutch y Luke examinan las runas. En los pinos escoceses muertos a la altura de la cintura, marcas talladas profundamente y oscurecidas con la edad. Hutch: <em>"Runas. ¿Recuerdas las de Gammelstad?"</em> Luke: <em>"Parece una B. ¿Cuántos años pueden tener los árboles?"</em> Hutch: <em>"Este pino puede vivir seiscientos años. Los vikingos usaban las runas hace unos mil. Pero alguien sabía cómo usarlas después."</em> Phil: <em>"No way. It's all wrong. Wrong."</em> Dom: son lo último en su lista de prioridades.<br><br>Debate de ruta. Dom arrebata el mapa de manos de Hutch. Luke defiende retroceder el camino de entrada (garantía de salida conocida). Dom: imposible, dos días más de caminata con la rodilla reventada. Hutch: el sendero antiguo debe de ir a algún sitio con sentido — nadie traza un camino que no lleva a ninguna parte. Decisión final: seguir el sendero hacia el oeste. Si no abre hacia el sur en algún punto, se revalora. Phil, sin girarse: <em>"The last thing we want is to be in here again at night."</em>`
  },
  {
    chapter: 18,
    title: `Capítulo 18 — Caminando y el Sueño de Hutch`,
    summary: `Alejándose de la casa, Hutch apoya a Dom y no puede dejar de revivir el sueño. Lo ve como una película: dos figuras viejas con dientes sucios en la planta baja diciéndole <em>"Don't keep him waiting. Your clothes are in the fire."</em> Luego escalando las escaleras como un niño pequeño, desnudo, pies descalzos y ennegrecidos sobre la madera mojada. En el desván rojo: huesos en el suelo, algunos con trozos grises todavía pegados. El olor a estiércol en paja, sudor de ganado, azufre. La criatura en la caja: pezuñas negras tan anchas como las de un caballo golpeando el borde de madera con emoción creciente — <em>clac clac clac</em>. Una ranura circular lisa tallada en el frente de la caja, para apoyar el cuello. El cráneo de alguien en la paja entre las patas negras. Hutch se acercó a la ranura. Las pezuñas se elevaron. Luke lo despertó.<br><br>Las manos todavía le tiemblan. Dom llama a Luke desde más adelante — Luke señala dos formas oscuras entre la maleza.`
  },
  {
    chapter: 19,
    title: `Capítulo 19 — El Asentamiento y la Piedra`,
    summary: `Dos horas de marcha al oeste. Luke lleva la cabeza. Dos edificios oscuros entre el sotobosque — tablas negras, ventanas, sugestión de chimenea. Impenetrable manto de ortigas y ramas entre el sendero y las fachadas. Dom: <em>"Sigue. No quiero saber lo que hay dentro."</em> Hutch empuja el pie bajo el helecho: surcos de ruedas de carro. <em>"Un asentamiento abandonado. Este sendero los unía."</em> Siguen adelante.<br><br>Luke propone ir por delante solo. Veinte minutos fuera del alcance auditivo, el sendero empieza a retorcerse y a subir y bajar sobre terreno irregular. Un árbol caído cada seis metros. El pecho duele. La rabia contra Hutch sube — los labios se mueven, dice cosas que después lo avergonzarán. Luego la rabia se drena dejándolo frío. La sed: el agua se acabó hace más de una hora. El miedo de haberse salido del sendero y no poder volver a encontrar a los demás.<br><br>Contempla la opción de ir a buscar ayuda en solitario si los árboles no abren. Solo. Sin que Hutch lo autorice si es necesario.<br><br>Treinta minutos después de perder de vista al grupo, tropieza con un plinto de granito cubierto de hiedra.`
  },
  {
    chapter: 20,
    title: `Capítulo 20 — El Silencio y la Brújula`,
    summary: `Hutch lo nota gradualmente: el bosque está completamente en silencio. Los pájaros que seguían con su charla esporádica callaron en el momento en que pasaron junto a los dos edificios del asentamiento. Sin brisa. Solo el arrastrar de pies, el suave repiqueteo de la lluvia y el golpe de hojas contra la tela. Hutch imagina el bosque conteniendo la respiración <em>"in anticipation."</em> Decide no decírselo a Dom y Phil.<br><br>El sendero parece disolverse en huecos sombríos engañosos. La luz ha caído — el dosel tan denso que bloquea casi todo. Hutch se preocupa por Luke, solo por delante. <em>"Para."</em><br><br>Dom: <em>"¿Eh?"</em> Phil para, su respiración asmática. Hutch saca la brújula. Noroeste. Quiere gritar. Se han desviado de nuevo — de forma incremental e imperceptible mientras cargaba con el peso de Dom. Están adentrándose en el bosque, no saliendo. Deja caer las manos sobre los muslos: <em>"No good."</em> Dom: <em>"What isn't?"</em> Hutch: <em>"This direction."</em> Una pausa. <em>"Shit."</em>`
  }
];
